void q1_soma(int *a, int *b, int *resultado, char *simbolo);
void q2_subtracao(int *a, int *b, int *resultado, char *simbolo);
void q3_multiplicacao(int *a, int *b, int *resultado, char *simbolo);
void q4_divisao(double *a, double *b, double *resultado, char *simbolo);
void q5_resto(int *a, int *b, int *resultado, char *simbolo);
void q6_potencia(int *a, int *b, long long int *resultado, char *simbolo);
void q7_fatorial(long long int *a, long long int *resultado, char *simbolo);
void q8_and_bit_a_bit(int *a, int *b, int *resultado, char *simbolo);
void q9_or(int *a, int *b, int *resultado, char *simbolo);
void q10_XOR(int *a, int *b, int *resultado, char *simbolo);
void q11_shift_direita(int *a, int *b, int *resultado, char *simbolo);
void q12_shift_esquerda(int *a, int *b, int *resultado, char *simbolo);
void q13_media(int *a, int *b, double *resultado, char *simbolo);
void q14_somatorio_invervalo(int *a, int *b, int *resultado, char *simbolo);
void q15_produtorio_de_um_intervalo(int *a, int *b, long long int *resultado, char *simbolo);
void q16_minimo(int *a, int *b, int *resultado, char *simbolo);
void q17_max(int *a, int *b, int *resultado, char *simbolo);
void q18_abs(int *a, int *resultado, char *simbolo);
void q19_igualdade(int *a, int *b, int *resultado, char *simbolo);
void q20_diferenca(int *a, int *b, int *resultado, char *simbolo);
void q21_maior_que(int *a, int *b, int *resultado, char *simbolo);
void q22_menor_que(int *a, int *b, int *resultado, char *simbolo);
void q23_maior_igual(int *a, int *b, int *resultado, char *simbolo);
void q24_menor_igual(int *a, int *b, int *resultado, char *simbolo);
void q25_and(int *a, int *b, int *resultado, char *simbolo);
void q26_nand(int *a, int *b, int *resultado, char *simbolo);
void q27_or(int *a, int *b, int *resultado, char *simbolo);
void q28_nor(int *a, int *b, int *resultado, char *simbolo);